/********************************************************************************************
* Hello Java
*********************************************************************************************
* Jacob Dodoo
* 08/24/22
*CMSC-255-001
********************************************************************************************/

public class Hello {
	public static void main(String[] args) {

	
		System.out.println("Jacob D");
		System.out.println("Hello.Java ");
		System.out.println("Display this text");
		System.out.println("08/24/22");
		System.out.println("CMSC-255-001");
		System.out.println();
	}
}